# ==============================
# Spring Boot 기본 설정
# ==============================
spring:
  application:
    name: realtime-fin-mq # 애플리케이션 이름
  kafka:
    bootstrap-servers: 127.0.0.1:19092 # Kafka 브로커 주소

    # Producer
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true

    # Consumer
    consumer:
      group-id: finance-mq-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 100
      auto-offset-reset: latest

# ==============================
# Kafka 설정
# ==============================
kafka:
  topic: financial-transactions       # 테스트용 토픽 이름

# ==============================
# 커스텀 MQ 설정
# ==============================
custom-mq:
  queue-size: 10000          # InMemoryQueue 용량
  dlq-size: 1000             # DLQ 용량
  poll-interval-ms: 100      # MyMQ 소비 주기
  num-consumers: 1           # 소비자 스레드 수

# ==============================
# Actuator 설정 (모니터링)
# ==============================
management:
  endpoints:
    web:
      exposure:
        include: '*'    # 모든 엔드포인트 활성화
  endpoint:
    health:
      show-details: always  # health check 세부정보 표시

# ==============================
# 로깅 설정
# ==============================
logging:
  level:
    root: INFO
    com.realtimefinmq: DEBUG
    org.springframework.kafka.listener: INFO